"""Reports API router."""

from fastapi import APIRouter, Depends, Query, Request
from sqlalchemy.orm import Session
from typing import List

from app.database import get_db
from app.services.report_service import ReportService
from app.services.audit_service import AuditService
from app.schemas.report import ReportResponse, ReportCreateRequest
from app.api.deps import get_current_user, require_manager
from app.models.user import User

router = APIRouter()


@router.get("/", response_model=List[ReportResponse])
def get_reports(db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    """List all reports generated by the current user."""
    service = ReportService(db)
    return service.get_reports(user.id)


@router.post("/generate", response_model=ReportResponse)
def generate_report(
    request: Request,
    data: ReportCreateRequest,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """Generate a PDF or CSV report on-demand."""
    service = ReportService(db)
    result = service.generate_report(user.id, data.report_type, data.format)
    AuditService.log_action(
        db=db,
        user_id=user.id,
        action="export",
        resource_type="report",
        resource_id=result.id,
        description=f"Generated {data.format.upper()} report ({data.report_type})",
        new_value={"report_type": data.report_type, "format": data.format},
        ip_address=request.client.host if request.client else None,
        user_agent=request.headers.get("user-agent"),
    )
    return result


@router.delete("/{report_id}", dependencies=[Depends(require_manager)])
def delete_report(
    request: Request,
    report_id: str,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """Delete a generated report."""
    service = ReportService(db)
    service.delete_report(user.id, report_id)
    AuditService.log_action(
        db=db,
        user_id=user.id,
        action="delete",
        resource_type="report",
        resource_id=report_id,
        description="Deleted generated report",
        ip_address=request.client.host if request.client else None,
        user_agent=request.headers.get("user-agent"),
    )
    return {"message": "Report deleted successfully"}

